---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test
  iam_profile_name: test-ec2dnsserver

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12
  client_rb:
    environment: test
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[et_hostname::default]
      - recipe[test-tools::default]
      - recipe[mock-ec2::default]
      - recipe[ec2dnsserver::default]
      - recipe[test-data::default]
      - recipe[shinken::default]
      - recipe[shinken::webui]
      - recipe[shinken::broker]
    driver:
      tags:
        Name: shinken-default-<%= ENV['USER'] %>-ubuntu-1404
    attributes:
      shinken:
        host_defaults:
          event_handler: notify_slack_for_host!#ops
          event_handler_enabled: 1
        hosts:
          - host_name: stage-api
            address: stage-api.evertrue.com
            active_checks_enabled: 0
            passive_checks_enabled: 0
            flap_detection_enabled: 0
        services:
          auth:
            host_name: stage-api
            service_description: Auth API Stage
            check_command: check_https!443!/auth/health
        install_type: source
      ec2dnsserver:
        contact_email: 'hostmaster@yourdomain.local'
        recursion_clients:
          - 192.168.19.0/24
        avoid_subnets: []
        zones:
          vagrantup.com: {}
          test-dns.local:
            stub: true
            ns_zone: local
            static_records:
              value: 192.168.33.11
              type: A
