name             'shinken'
maintainer       'EverTrue, Inc.'
maintainer_email 'devops@evertrue.com'
license          'Apache 2.0'
description      'Installs/Configures shinken'
long_description 'Installs/Configures shinken'
version          '2.4.3'

depends 'ark'
depends 'apt'
depends 'build-essential'
